kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # IMPORTANT, mapping the host port and containerPort here, can be multiple as below.
    hostPort: 80
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 443
    hostPort: 443
  - containerPort: 8081
    hostPort: 8081
  - containerPort: 8082
    hostPort: 8082
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 3000
    hostPort: 3000
  #Add this for PV/PVC
  extraMounts:
    - hostPath: /home/jsflzhong/kind/data
      containerPath: /kindData
